apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-credentials
  namespace: {{ .Values.externalSecrets.datadogNamespace | quote }}
  labels:
    app.kubernetes.io/part-of: oficina
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.datadogSecretName | quote }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api-key
      remoteRef:
        key: {{ required "externalSecrets.datadogSecretArn is required" .Values.externalSecrets.datadogSecretArn | quote }}
        property: api_key
    - secretKey: app-key
      remoteRef:
        key: {{ .Values.externalSecrets.datadogSecretArn | quote }}
        property: app_key
